---
- name: Setup For mariadb
  hosts: db
  gather_facts: no
  become: yes

    - name: install mysql
      yum:
        name:
         - python3-PyMySQL
         - MySQL-python
         - mariadb-server
         - mysql

    - name: start mysql
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: create DB
      mysql_db:
        name: "wpDB"
        state: present

    - name: create user
      mysql_user:
        name: "wpuser"
        password: "1234"
        priv: "*.*:ALL"
        state: present
        host: '%'

