---
- name: Setup For Wordpress
  hosts: wp
  gather_facts: no
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: packages
      yum:
        name:
          - unzip
          - yum-utils
        state: present

    - name: remi-repo
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: yum-config-manager
      shell: "{{ item }}"
      with_items:
        - "yum-config-manager --enable remi-php73"


    - name: download wordpress
      get_url:
        url: http://wordpress.org/latest.zip
        dest: /var/www/html/latest.zip

    - name: unzip
      unarchive:
        src: /var/www/html/latest.zip
        remote_src: true
        dest: /var/www/html

    - name: directory change
      shell: "{{ item }}"
      with_items:
        - "cp -R /var/www/html/wordpress/* /var/www/html"

    - name: install php , phpmysql
      yum:
        name:
          - php
          - php-mysql

    - name: wp config
      shell: "{{ item }}"
      with_items:
        - "cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php"
        - "sed -i 's/database_name_here/wpDB/g' /var/www/html/wp-config.php"
        - "sed -i 's/username_here/wpuser/g' /var/www/html/wp-config.php"
        - "sed -i 's/password_here/1234/g' /var/www/html/wp-config.php"
        - "sed -i 's/localhost/172.16.1.13/g' /var/www/html/wp-config.php"
        - "setenforce 0"
    - name: install mysql
      yum:
        name:
         - mysql

    - name: start httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
